# Autogenerated wrapper script for libfreenect_jll for x86_64-w64-mingw32
export libfreenect_sync, lifreenect

using libusb_jll
JLLWrappers.@generate_wrapper_header("libfreenect")
JLLWrappers.@declare_library_product(libfreenect_sync, "libfreenect_sync.dll")
JLLWrappers.@declare_library_product(lifreenect, "libfreenect.dll")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_library_product(
        libfreenect_sync,
        "bin\\libfreenect_sync.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lifreenect,
        "bin\\libfreenect.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
